# Generated by Django 3.2.8 on 2021-10-28 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentalGroup',
            fields=[
                ('group_code', models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='Group Code')),
                ('group_name', models.CharField(max_length=300, verbose_name='Group Name')),
            ],
            options={
                'ordering': ['group_name'],
            },
        ),
        migrations.CreateModel(
            name='Directorate',
            fields=[
                ('directorate_code', models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='Directorate Code')),
                ('directorate_name', models.CharField(max_length=300, verbose_name='Directorate Name')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='directorates', to='chartofaccount.departmentalgroup')),
            ],
            options={
                'ordering': ['directorate_name'],
            },
        ),
        migrations.CreateModel(
            name='CostCentre',
            fields=[
                ('cost_centre_code', models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='Cost Centre Code')),
                ('cost_centre_name', models.CharField(max_length=300, verbose_name='Cost Centre Name')),
                ('directorate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_centres', to='chartofaccount.directorate')),
            ],
            options={
                'ordering': ['cost_centre_code'],
            },
        ),
    migrations.CreateModel(
        name='ProgrammeCode',
        fields=[
            ('programme_code',
             models.CharField(max_length=50, primary_key=True, serialize=False,
                              verbose_name='Programme Code')),
            ('programme_description',
             models.CharField(max_length=100, verbose_name='Programme Name')),
        ],
        options={
            'verbose_name_plural': 'Programme Codes',
            'ordering': ['programme_code'],
        },
    ),
    migrations.CreateModel(
        name='ProjectCode',
        fields=[
            ('project_code',
             models.CharField(max_length=50, primary_key=True, serialize=False,
                              verbose_name='Project Code')),
            ('project_description',
             models.CharField(max_length=300, verbose_name='Project Description')),
        ],
        options={
            'verbose_name': 'Project',
            'verbose_name_plural': 'Projects',
            'ordering': ['project_code'],
        },
    ),
    ]