# Generated by Django 3.2.8 on 2021-10-29 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chartofaccount', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costcentre',
            name='directorate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_centres', to='chartofaccount.directorate'),
        ),
        migrations.AlterField(
            model_name='directorate',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='directorates', to='chartofaccount.departmentalgroup'),
        ),
    ]
