# Generated by Django 3.2.11 on 2022-01-21 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chartofaccount", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="costcentre",
            name="directorate",
        ),
        migrations.AlterField(
            model_name="costcentre",
            name="cost_centre_code",
            field=models.CharField(max_length=6, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="costcentre",
            name="cost_centre_name",
            field=models.CharField(max_length=64),
        ),
    ]
