# Generated by Django 3.2.11 on 2022-02-03 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("change_log", "0002_auto_20220202_1535"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="change",
            options={"get_latest_by": "timestamp", "ordering": ["-timestamp"]},
        ),
    ]
