# Generated by Django 3.2.12 on 2022-03-03 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("event_log", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="event",
            options={"ordering": ["-timestamp"]},
        ),
    ]
