# Generated by Django 3.2.7 on 2021-10-04 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('django_workflow_engine', '0002_alter_flow_workflow_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractorApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_ir35', models.BooleanField(null=True)),
                ('flow', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='django_workflow_engine.flow')),
            ],
        ),
    ]
