# Generated by Django 3.2.7 on 2021-10-04 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_workflow_engine', '0002_alter_flow_workflow_name'),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractorapproval',
            name='flow',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contractor_approval', to='django_workflow_engine.flow'),
        ),
    ]
