# Generated by Django 3.2.8 on 2021-11-01 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_auto_20211025_1625"),
    ]

    operations = []
