# Generated by Django 3.2.8 on 2021-10-21 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20211020_1522'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatementOfWorkModuleDeliverable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deliverable_title', models.CharField(max_length=255)),
                ('deliverable_description', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('monthly_fee', models.DecimalField(decimal_places=2, max_digits=9)),
                ('payment_date', models.DateField()),
                ('statement_of_work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliverable', to='main.statementofwork')),
            ],
        ),
        migrations.CreateModel(
            name='StatementOfWorkModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_title', models.CharField(max_length=255)),
                ('completion_date', models.DateField()),
                ('statement_of_work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module', to='main.statementofwork')),
            ],
        ),
    ]
