# Generated by Django 3.2.8 on 2021-10-08 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_alter_contractorapproval_flow"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contractorapproval",
            name="is_ir35",
            field=models.BooleanField(
                choices=[(True, "Yes"), (False, "No")], null=True
            ),
        ),
        migrations.CreateModel(
            name="JobDescription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="Vacancy Title"),
                ),
                (
                    "role_purpose",
                    models.TextField(
                        help_text="Use this space to outline what the person is responsible for delivering and how this contributes to the success of the department. More detail on this will be added in the next section."
                    ),
                ),
                (
                    "key_accountabilities",
                    models.TextField(
                        help_text="Outline what the individual needs to do in order to achieve to deliverables outlined above."
                    ),
                ),
                ("line_management_responsibility", models.TextField()),
                (
                    "personal_attributes_and_skills",
                    models.TextField(
                        help_text="Insert information about what the ideal candidate would be like in their character and what they’d bring to your team. This will enhance our search ability and interview quality."
                    ),
                ),
                (
                    "essential_and_preferred_experience",
                    models.TextField(
                        help_text="You must ensure the successful candidate meets your specification entirely, so do not put expectations that are not vital.\n\nThe diversity of applicants you receive to roles increases when shorter lists of personal and experience requirements are listed, which creates a better pool of candidates to select from at interview."
                    ),
                ),
                (
                    "approval",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="statement_of_work",
                        to="main.contractorapproval",
                    ),
                ),
            ],
        ),
    ]
