# Generated by Django 3.2.8 on 2021-10-28 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chartofaccount', '0001_initial'),
        ('main', '0002_auto_20211025_1625'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interimrequest',
            name='todo',
        ),
        migrations.AddField(
            model_name='interimrequest',
            name='contractor_type',
            field=models.CharField(choices=[('generalist', 'Generalist'), ('specialist', 'Specialist')], max_length=50, verbose_name='Category of Interim'),
            
        ),
        migrations.AddField(
            model_name='interimrequest',
            name='cost_centre_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='costcentres', to='chartofaccount.costcentre', verbose_name='Cost Centre/Team'),
            
        ),
        migrations.AddField(
            model_name='interimrequest',
            name='directorate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='directorates', to='chartofaccount.directorate'),
            
        ),
        migrations.AddField(
            model_name='interimrequest',
            name='end_date',
            field=models.DateField(verbose_name='Anticipated End Date'),
            
        ),
        migrations.AddField(
            model_name='interimrequest',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='chartofaccount.departmentalgroup'),
            
        ),
        migrations.AddField(
            model_name='interimrequest',
            name='name_of_contractor',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='If Nominated Worker - please provide Name of the contractor'),
        ),
        migrations.AddField(
            model_name='interimrequest',
            name='new_requirement',
            field=models.BooleanField(verbose_name='New'),
            
        ),
        migrations.AddField(
            model_name='interimrequest',
            name='overseas_country',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='if Overseas which Country'),
        ),
        migrations.AddField(
            model_name='interimrequest',
            name='part_b_business_case',
            field=models.TextField(verbose_name='Business Case: Please detail why the interim resource is required.'),
            
        ),
        migrations.AddField(
            model_name='interimrequest',
            name='part_b_impact',
            field=models.TextField(verbose_name='What would be the impact of not filling this requirement.'),
            
        ),
        migrations.AddField(
            model_name='interimrequest',
            name='part_b_main_reason',
            field=models.TextField(verbose_name='What are the main reasons why this role has not been filled by a substantive Civil Servant. Please detail the strategic workforce plan for this role after the assignment end date:'),
            
        ),
        migrations.AddField(
            model_name='interimrequest',
            name='project_name_role_title',
            field=models.CharField(max_length=255, verbose_name='Project name/ Title of the Role'),
            
        ),
        migrations.AddField(
            model_name='interimrequest',
            name='slot_codes',
            field=models.CharField(max_length=255),
            
        ),
        migrations.AddField(
            model_name='interimrequest',
            name='start_date',
            field=models.DateField(verbose_name='Anticipated Start Date'),
            
        ),
        migrations.AddField(
            model_name='interimrequest',
            name='type_of_security_clearance',
            field=models.CharField(choices=[('BPSS', 'BPSS'), ('sc', 'SC'), ('dv', 'DV'), ('ctc', 'CTC')], max_length=50, verbose_name='Level of Security clearance required'),
            
        ),
        migrations.AddField(
            model_name='interimrequest',
            name='uk_based',
            field=models.BooleanField(verbose_name='UK based'),
        ),
    ]
