# Generated by Django 3.2.8 on 2021-11-01 14:23

from django.db import migrations


def create_groups(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Permission = apps.get_model("auth", "Permission")

    Group.objects.all().delete()

    Group.objects.bulk_create(
        [
            Group(pk=1, name="Hiring Manager"),
            Group(pk=2, name="Approver"),
            Group(pk=3, name="Head of Profession"),
            Group(pk=4, name="Chief"),
            Group(pk=5, name="BusOps"),
            Group(pk=6, name="HRBP"),
            Group(pk=7, name="Finance"),
            Group(pk=8, name="Commercial"),
        ]
    )

    # Hiring Manager
    Group.objects.get(pk=1).permissions.set(
        Permission.objects.filter(
            codename__in=[
                # resourcingrequest
                "add_resourcingrequest",
                "view_resourcingrequest",
                "change_resourcingrequest",
                "delete_resourcingrequest",
                # jobdescription
                "add_jobdescription",
                "view_jobdescription",
                "change_jobdescription",
                "delete_jobdescription",
                # statementofwork
                "add_statementofwork",
                "view_statementofwork",
                "change_statementofwork",
                "delete_statementofwork",
                # interimrequest
                "add_interimrequest",
                "view_interimrequest",
                "change_interimrequest",
                "delete_interimrequest",
                # cestrationale
                "add_cestrationale",
                "view_cestrationale",
                "change_cestrationale",
                "delete_cestrationale",
                # sdsstatusdetermination
                "add_sdsstatusdetermination",
                "view_sdsstatusdetermination",
                "change_sdsstatusdetermination",
                "delete_sdsstatusdetermination",
                # comment
                "add_comment",
                "view_comment",
                "change_comment",
                "delete_comment",
            ],
            content_type__app_label="main",
        )
    )

    # Approver
    Group.objects.get(pk=2).permissions.set(
        Permission.objects.filter(
            codename__in=[
                "view_resourcingrequest",
                "view_jobdescription",
                "view_statementofwork",
                "view_interimrequest",
                "view_cestrationale",
                "view_sdsstatusdetermination",
                # comment
                "add_comment",
                "view_comment",
                "change_comment",
                "delete_comment",
            ],
            content_type__app_label="main",
        )
    )

    # Head of Profession
    Group.objects.get(pk=3).permissions.set(
        [
            Permission.objects.get(
                codename="can_give_head_of_profession_approval",
                content_type__app_label="main",
            )
        ]
    )

    # Chief
    Group.objects.get(pk=4).permissions.set(
        [
            Permission.objects.get(
                codename="can_give_chief_approval",
                content_type__app_label="main",
            )
        ]
    )

    # BusOps
    Group.objects.get(pk=5).permissions.set(
        [
            Permission.objects.get(
                codename="can_give_busops_approval",
                content_type__app_label="main",
            )
        ]
    )

    # HRBP
    Group.objects.get(pk=6).permissions.set(
        [
            Permission.objects.get(
                codename="can_give_hrbp_approval",
                content_type__app_label="main",
            )
        ]
    )

    # Finance
    Group.objects.get(pk=7).permissions.set(
        [
            Permission.objects.get(
                codename="can_give_finance_approval",
                content_type__app_label="main",
            )
        ]
    )

    # Commercial
    Group.objects.get(pk=8).permissions.set(
        [
            Permission.objects.get(
                codename="can_give_commercial_approval",
                content_type__app_label="main",
            )
        ]
    )


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_auto_20211025_1625"),
    ]

    operations = [
        migrations.RunPython(create_groups),
    ]
