# Generated by Django 3.2.8 on 2021-10-25 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_statementofworkmodule_statementofworkmoduledeliverable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statementofworkmoduledeliverable',
            name='statement_of_work',
        ),
        migrations.AddField(
            model_name='statementofworkmoduledeliverable',
            name='statement_of_work_module',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='deliverables', to='main.statementofworkmodule'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='statementofworkmodule',
            name='statement_of_work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='main.statementofwork'),
        ),
    ]
