# Generated by Django 3.2.8 on 2021-11-02 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20211101_1734'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statementofwork',
            name='team_directorate',
        ),
        migrations.AddField(
            model_name='statementofwork',
            name='directorate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statement_of_work_directorates', to='chartofaccount.directorate'),
            
        ),
        migrations.AddField(
            model_name='statementofwork',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statement_of_work_groups', to='chartofaccount.departmentalgroup'),
            
        ),
        migrations.AlterField(
            model_name='interimrequest',
            name='cost_centre_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interim_request_costcentres', to='chartofaccount.costcentre', verbose_name='Cost Centre/Team'),
        ),
        migrations.AlterField(
            model_name='interimrequest',
            name='directorate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interim_request_directorates', to='chartofaccount.directorate'),
        ),
        migrations.AlterField(
            model_name='interimrequest',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interim_request_groups', to='chartofaccount.departmentalgroup'),
        ),
        migrations.AlterField(
            model_name='statementofwork',
            name='cost_centre_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statement_of_work_costcentres', to='chartofaccount.costcentre', verbose_name='Cost Centre/Team'),
        ),
        migrations.AlterField(
            model_name='statementofwork',
            name='programme_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statement_of_work_programmes', to='chartofaccount.programmecode'),
        ),
        migrations.AlterField(
            model_name='statementofwork',
            name='project_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='statement_of_work_projects', to='chartofaccount.projectcode'),
        ),
    ]
