# Generated by Django 3.2.8 on 2021-10-11 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_auto_20211008_1104"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobdescription",
            name="approval",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="job_description",
                to="main.contractorapproval",
            ),
        ),
    ]
