# Generated by Django 3.2.8 on 2021-11-02 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chartofaccount", "0001_initial"),
        ("main", "0004_auto_20211102_0728"),
    ]

    operations = [
        migrations.AlterField(
            model_name="interimrequest",
            name="cost_centre_code",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="chartofaccount.costcentre",
                verbose_name="Cost Centre/Team",
            ),
        ),
        migrations.AlterField(
            model_name="interimrequest",
            name="directorate",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="chartofaccount.directorate",
            ),
        ),
        migrations.AlterField(
            model_name="interimrequest",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="chartofaccount.departmentalgroup",
            ),
        ),
        migrations.AlterField(
            model_name="interimrequest",
            name="uk_based",
            field=models.BooleanField(
                choices=[(True, "Yes"), (False, "No")],
                default=True,
                verbose_name="UK based",
            ),
        ),
        migrations.AlterField(
            model_name="statementofwork",
            name="cost_centre_code",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="chartofaccount.costcentre",
                verbose_name="Cost Centre/Team",
            ),
        ),
        migrations.AlterField(
            model_name="statementofwork",
            name="directorate",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="chartofaccount.directorate",
            ),
        ),
        migrations.AlterField(
            model_name="statementofwork",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="chartofaccount.departmentalgroup",
            ),
        ),
        migrations.AlterField(
            model_name="statementofwork",
            name="programme_code",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="chartofaccount.programmecode",
            ),
        ),
        migrations.AlterField(
            model_name="statementofwork",
            name="project_code",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="chartofaccount.projectcode",
            ),
        ),
    ]
