# Generated by Django 3.2.8 on 2021-10-12 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_alter_jobdescription_approval"),
    ]

    operations = [
        migrations.AddField(
            model_name="contractorapproval",
            name="name",
            field=models.CharField(default="Legacy", max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="contractorapproval",
            name="is_ir35",
            field=models.BooleanField(
                choices=[(True, "Yes"), (False, "No")],
                null=True,
                verbose_name="Is the role inside IR35?",
            ),
        ),
    ]
