# Generated by Django 3.2.8 on 2021-10-12 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_auto_20211012_1550"),
    ]

    operations = [
        migrations.AddField(
            model_name="contractorapproval",
            name="chief_approval",
            field=models.BooleanField(
                choices=[(True, "Yes"), (False, "No")], null=True
            ),
        ),
        migrations.AddField(
            model_name="contractorapproval",
            name="commercial_approval",
            field=models.BooleanField(
                choices=[(True, "Yes"), (False, "No")], null=True
            ),
        ),
        migrations.AddField(
            model_name="contractorapproval",
            name="finance_approval",
            field=models.BooleanField(
                choices=[(True, "Yes"), (False, "No")], null=True
            ),
        ),
        migrations.AddField(
            model_name="contractorapproval",
            name="hrbp_approval",
            field=models.BooleanField(
                choices=[(True, "Yes"), (False, "No")], null=True
            ),
        ),
    ]
