# Generated by Django 3.2.8 on 2021-11-02 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_data_groups"),
        ("main", "0005_auto_20211102_1156"),
    ]

    operations = []
