# Generated by Django 3.2.8 on 2021-10-12 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_auto_20211012_1655"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contractorapproval",
            name="hrbp_approval",
            field=models.BooleanField(
                choices=[(True, "Yes"), (False, "No")],
                null=True,
                verbose_name="HRBP approval",
            ),
        ),
    ]
