# Generated by Django 3.2.8 on 2021-10-13 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_alter_contractorapproval_hrbp_approval"),
    ]

    operations = [
        migrations.CreateModel(
            name="StatementOfWork",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=255)),
                (
                    "approval",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="statement_of_work",
                        to="main.contractorapproval",
                    ),
                ),
            ],
        ),
    ]
