# Generated by Django 3.2.8 on 2021-11-05 11:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20211104_1416'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sdsstatusdetermination',
            old_name='todo',
            new_name='reasons',
        ),
        migrations.AddField(
            model_name='sdsstatusdetermination',
            name='agency',
            field=models.CharField(max_length=255),
        ),
        migrations.AddField(
            model_name='sdsstatusdetermination',
            name='company_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AddField(
            model_name='sdsstatusdetermination',
            name='completed_by',
            field=models.CharField(max_length=255),
        ),
        migrations.AddField(
            model_name='sdsstatusdetermination',
            name='date_completed',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='sdsstatusdetermination',
            name='end_date',
            field=models.DateField(verbose_name='Contract End Date'),
        ),
        migrations.AddField(
            model_name='sdsstatusdetermination',
            name='on_behalf_of',
            field=models.CharField(max_length=255),
        ),
        migrations.AddField(
            model_name='sdsstatusdetermination',
            name='start_date',
            field=models.DateField(verbose_name='Contract/Extension Start Date'),
        ),
        migrations.AddField(
            model_name='sdsstatusdetermination',
            name='worker_name',
            field=models.CharField(max_length=255),
        ),
    ]
