# Generated by Django 3.2.8 on 2021-11-08 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20211105_1146'),
    ]

    operations = [
        migrations.CreateModel(
            name='CestDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('resourcing_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cest_document', to='main.resourcingrequest')),
            ],
        ),
    ]
