# Generated by Django 3.2.8 on 2021-10-13 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0008_statementofwork"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contractorapproval",
            options={
                "permissions": (
                    ("can_give_chief_approval", "Can give chief approval"),
                    ("can_give_hrbp_approval", "Can give HRBP approval"),
                    ("can_give_finance_approval", "Can give finance approval"),
                    ("can_give_commercial_approval", "Can give commercial approval"),
                )
            },
        ),
        migrations.AlterField(
            model_name="contractorapproval",
            name="chief_approval",
            field=models.BooleanField(
                choices=[(True, "Yes"), (False, "No")], default=False
            ),
        ),
        migrations.AlterField(
            model_name="contractorapproval",
            name="commercial_approval",
            field=models.BooleanField(
                choices=[(True, "Yes"), (False, "No")], default=False
            ),
        ),
        migrations.AlterField(
            model_name="contractorapproval",
            name="finance_approval",
            field=models.BooleanField(
                choices=[(True, "Yes"), (False, "No")], default=False
            ),
        ),
        migrations.AlterField(
            model_name="contractorapproval",
            name="hrbp_approval",
            field=models.BooleanField(
                choices=[(True, "Yes"), (False, "No")],
                default=False,
                verbose_name="HRBP approval",
            ),
        ),
    ]
