# Generated by Django 3.2.8 on 2021-10-13 13:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("main", "0009_auto_20211013_1231"),
    ]

    operations = [
        migrations.AddField(
            model_name="contractorapproval",
            name="chief_approval_when",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="contractorapproval",
            name="chief_approval_who",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="user.user",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="contractorapproval",
            name="commercial_approval_when",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="contractorapproval",
            name="commercial_approval_who",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="user.user",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="contractorapproval",
            name="finance_approval_when",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="contractorapproval",
            name="finance_approval_who",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="user.user",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="contractorapproval",
            name="hrbp_approval_when",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="contractorapproval",
            name="hrbp_approval_who",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="user.user",
            ),
            preserve_default=False,
        ),
    ]
