# Generated by Django 3.2.8 on 2021-11-09 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0009_cestdocument"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cestdocument",
            name="file",
            field=models.FileField(
                help_text="The link to the document is only valid for 5 minutes. After this, you will need to refresh the page to get a new link.",
                upload_to="uploads/",
            ),
        ),
    ]
