# Generated by Django 3.2.8 on 2021-10-13 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0011_auto_20211013_1348"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contractorapproval",
            name="chief_approval",
            field=models.BooleanField(
                choices=[(True, "Yes"), (False, "No")], null=True
            ),
        ),
        migrations.AlterField(
            model_name="contractorapproval",
            name="commercial_approval",
            field=models.BooleanField(
                choices=[(True, "Yes"), (False, "No")], null=True
            ),
        ),
        migrations.AlterField(
            model_name="contractorapproval",
            name="finance_approval",
            field=models.BooleanField(
                choices=[(True, "Yes"), (False, "No")], null=True
            ),
        ),
        migrations.AlterField(
            model_name="contractorapproval",
            name="hrbp_approval",
            field=models.BooleanField(
                choices=[(True, "Yes"), (False, "No")],
                null=True,
                verbose_name="HRBP approval",
            ),
        ),
    ]
