# Generated by Django 3.2.8 on 2021-11-10 13:36

from django.db import migrations, models


def migrate_state(apps, schema_editor):
    ResourcingRequest = apps.get_model("main", "ResourcingRequest")
    ResourcingRequest.objects.filter(state=2).update(state=4)


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0011_alter_cestdocument_file"),
    ]

    operations = [
        migrations.RunPython(migrate_state),
        migrations.AlterField(
            model_name="resourcingrequest",
            name="state",
            field=models.SmallIntegerField(
                choices=[
                    (0, "Draft"),
                    (1, "Awaiting approvals"),
                    (2, "Amending"),
                    (3, "Amendments review"),
                    (4, "Approved"),
                ],
                default=0,
            ),
        ),
    ]
