# Generated by Django 3.2.8 on 2021-10-14 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0012_auto_20211013_1505"),
    ]

    operations = [
        migrations.AddField(
            model_name="contractorapproval",
            name="status",
            field=models.SmallIntegerField(
                choices=[(0, "Draft"), (1, "Ready")], default=1
            ),
            preserve_default=False,
        ),
    ]
