# Generated by Django 3.2.9 on 2021-11-16 15:52

import datetime

from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0013_alter_resourcingrequest_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="resourcingrequest",
            name="end_date",
            field=models.DateField(
                default=datetime.datetime(2022, 5, 15, 15, 51, 41, 43135, tzinfo=utc)
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="resourcingrequest",
            name="job_title",
            field=models.CharField(default="Python Developer", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="resourcingrequest",
            name="project_name",
            field=models.CharField(default="JML", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="resourcingrequest",
            name="start_date",
            field=models.DateField(
                default=datetime.datetime(2021, 11, 16, 15, 52, 22, 841471, tzinfo=utc)
            ),
            preserve_default=False,
        ),
    ]
