# Generated by Django 3.2.9 on 2021-11-16 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0014_auto_20211116_1552"),
    ]

    operations = [
        migrations.RenameField(
            model_name="resourcingrequest",
            old_name="name",
            new_name="full_name",
        ),
    ]
