# Generated by Django 3.2.8 on 2021-10-14 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0014_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="text",
            field=models.TextField(verbose_name="Add a comment"),
        ),
        migrations.AlterField(
            model_name="contractorapproval",
            name="status",
            field=models.SmallIntegerField(
                choices=[(0, "Draft"), (1, "Ready")], default=0
            ),
        ),
    ]
