# Generated by Django 3.2.8 on 2021-10-14 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0015_auto_20211014_1504"),
    ]

    operations = [
        migrations.CreateModel(
            name="SdsStatusDetermination",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("todo", models.TextField()),
                (
                    "approval",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sds_status_determination",
                        to="main.contractorapproval",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InterimRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("todo", models.TextField()),
                (
                    "approval",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interim_request",
                        to="main.contractorapproval",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CestRationale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("todo", models.TextField()),
                (
                    "approval",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cest_rationale",
                        to="main.contractorapproval",
                    ),
                ),
            ],
        ),
    ]
