# Generated by Django 3.2.8 on 2021-10-15 11:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0016_cestrationale_interimrequest_sdsstatusdetermination'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractorapproval',
            name='chief',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='user.user'),
            preserve_default=False,
        ),
    ]
