# Generated by Django 3.2.9 on 2021-11-19 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0017_resourcingrequest_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="resourcingrequest",
            name="days_required",
            field=models.IntegerField(
                null=True, verbose_name="Total number of days required"
            ),
        ),
        migrations.AddField(
            model_name="resourcingrequest",
            name="max_day_rate",
            field=models.IntegerField(
                null=True, verbose_name="Maximum anticipated day rate"
            ),
        ),
        migrations.AddField(
            model_name="resourcingrequest",
            name="min_day_rate",
            field=models.IntegerField(
                null=True, verbose_name="Minimum anticipated day rate"
            ),
        ),
        migrations.AddField(
            model_name="resourcingrequest",
            name="project_fees",
            field=models.IntegerField(
                null=True, verbose_name="Total project fees (exclude VAT)"
            ),
        ),
    ]
