# Generated by Django 3.2.8 on 2021-10-15 14:44

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0018_contractorapproval_check_status"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="contractorapproval",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("chief_approval_who", django.db.models.expressions.F("chief"))
                ),
                name="check_chief",
            ),
        ),
    ]
