# Generated by Django 3.2.8 on 2021-10-18 12:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("main", "0019_contractorapproval_check_chief"),
    ]

    operations = [
        migrations.AddField(
            model_name="contractorapproval",
            name="requestor",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="approvals",
                to="user.user",
            ),
            preserve_default=False,
        ),
    ]
