# Generated by Django 3.2.9 on 2021-11-19 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chartofaccount", "0001_initial"),
        ("main", "0019_auto_20211119_1257"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="interimrequest",
            name="cost_centre_code",
        ),
        migrations.RemoveField(
            model_name="interimrequest",
            name="end_date",
        ),
        migrations.RemoveField(
            model_name="interimrequest",
            name="name_of_contractor",
        ),
        migrations.RemoveField(
            model_name="interimrequest",
            name="new_requirement",
        ),
        migrations.RemoveField(
            model_name="interimrequest",
            name="project_name_role_title",
        ),
        migrations.RemoveField(
            model_name="interimrequest",
            name="start_date",
        ),
        migrations.RemoveField(
            model_name="resourcingrequest",
            name="days_required",
        ),
        migrations.RemoveField(
            model_name="resourcingrequest",
            name="max_day_rate",
        ),
        migrations.RemoveField(
            model_name="resourcingrequest",
            name="min_day_rate",
        ),
        migrations.RemoveField(
            model_name="resourcingrequest",
            name="project_fees",
        ),
        migrations.CreateModel(
            name="FinancialInformation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "area_of_work",
                    models.CharField(
                        choices=[
                            ("investment", "Investment"),
                            ("trade", "Trade"),
                            ("ddat", "DDaT"),
                            ("corporate", "Corporate"),
                        ],
                        max_length=255,
                        verbose_name="Area of work for VAT reclaim",
                    ),
                ),
                (
                    "total_budget",
                    models.IntegerField(
                        verbose_name="Total Budget, including sourcing fees, expenses and interim labour cost"
                    ),
                ),
                (
                    "timesheet_and_expenses_validator",
                    models.CharField(
                        max_length=255,
                        verbose_name="Name of the Timesheet & Expenses Validator",
                    ),
                ),
                (
                    "min_day_rate",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Minimum anticipated day rate",
                    ),
                ),
                (
                    "max_day_rate",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Maximum anticipated day rate",
                    ),
                ),
                (
                    "days_required",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Total number of days required",
                    ),
                ),
                (
                    "project_fees",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Total project fees (exclude VAT)",
                    ),
                ),
                (
                    "cost_centre_code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="chartofaccount.costcentre",
                        verbose_name="Cost Centre/Team",
                    ),
                ),
                (
                    "programme_code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="chartofaccount.programmecode",
                    ),
                ),
                (
                    "resourcing_request",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="financial_information",
                        to="main.resourcingrequest",
                    ),
                ),
            ],
        ),
    ]
