# Generated by Django 3.2.9 on 2021-11-19 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chartofaccount", "0001_initial"),
        ("main", "0020_auto_20211119_1542"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="interimrequest",
            name="directorate",
        ),
        migrations.RemoveField(
            model_name="interimrequest",
            name="group",
        ),
        migrations.AddField(
            model_name="financialinformation",
            name="directorate",
            field=models.ForeignKey(
                default="11111A",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="chartofaccount.directorate",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="financialinformation",
            name="group",
            field=models.ForeignKey(
                default="1111AA",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="chartofaccount.departmentalgroup",
            ),
            preserve_default=False,
        ),
    ]
