# Generated by Django 3.2.9 on 2021-11-22 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0023_alter_interimrequest_equivalent_civil_servant_grade"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cestrationale",
            name="role_end_date",
        ),
        migrations.RemoveField(
            model_name="cestrationale",
            name="role_start_date",
        ),
        migrations.RemoveField(
            model_name="cestrationale",
            name="worker_name",
        ),
        migrations.RemoveField(
            model_name="sdsstatusdetermination",
            name="end_date",
        ),
        migrations.RemoveField(
            model_name="sdsstatusdetermination",
            name="start_date",
        ),
        migrations.RemoveField(
            model_name="sdsstatusdetermination",
            name="worker_name",
        ),
        migrations.RemoveField(
            model_name="statementofwork",
            name="cost_centre_code",
        ),
        migrations.RemoveField(
            model_name="statementofwork",
            name="directorate",
        ),
        migrations.RemoveField(
            model_name="statementofwork",
            name="end_date",
        ),
        migrations.RemoveField(
            model_name="statementofwork",
            name="group",
        ),
        migrations.RemoveField(
            model_name="statementofwork",
            name="programme_code",
        ),
        migrations.RemoveField(
            model_name="statementofwork",
            name="start_date",
        ),
    ]
