# Generated by Django 3.2.9 on 2021-11-22 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0024_auto_20211122_1426"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="statementofwork",
            name="role",
        ),
    ]
