# Generated by Django 3.2.9 on 2021-11-23 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0025_remove_statementofwork_role"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="approval",
            options={
                "ordering": ["-timestamp"],
                "permissions": (
                    (
                        "can_give_head_of_profession_approval",
                        "Can give head of profession approval",
                    ),
                    ("can_give_busops_approval", "Can give BusOps approval"),
                    ("can_give_chief_approval", "Can give chief approval"),
                    ("can_give_hrbp_approval", "Can give HRBP approval"),
                    ("can_give_finance_approval", "Can give finance approval"),
                    ("can_give_commercial_approval", "Can give commercial approval"),
                    ("can_give_director_approval", "Can give director approval"),
                    (
                        "can_give_director_general_approval",
                        "Can give director general approval",
                    ),
                ),
            },
        ),
        migrations.AlterField(
            model_name="approval",
            name="type",
            field=models.CharField(
                choices=[
                    ("head_of_profession", "Head of Profession"),
                    ("chief", "Chief"),
                    ("busops", "BusOps"),
                    ("hrbp", "HRBP"),
                    ("finance", "Finance"),
                    ("commercial", "Commercial"),
                    ("director", "Director"),
                    ("director_general", "Director General"),
                ],
                max_length=20,
            ),
        ),
    ]
