# Generated by Django 3.2.9 on 2021-11-24 15:56

from django.db import migrations


EVENT_TYPES = (
    (1, "CREATED", "Created the resourcing request"),
    (2, "UPDATED", "Updated the resourcing request"),
    (3, "SENT_FOR_APPROVAL", "Sent the resourcing request for approval"),
    (4, "AMENDING", "Amending the resourcing request"),
    (5, "SENT_FOR_REVIEW", "Sent the amendments for review"),
    (6, "REVIEWED_AMENDMENTS", "Reviewed the amendments"),
    (7, "GROUP_APPROVED", "A group approved the resourcing request"),
    (8, "GROUP_REJECTED", "A group rejected the resourcing request"),
    (9, "COMMENTED", "Somebody commented on the resourcing request"),
    (10, "APPROVED", "The resourcing request was approved"),
)


def insert_event_types(apps, schema_editor):
    EventType = apps.get_model("event_log", "EventType")

    for pk, code, name in EVENT_TYPES:
        EventType.objects.create(pk=pk, code=code, name=name)


def delete_event_types(apps, schema_editor):
    EventType = apps.get_model("event_log", "EventType")

    EventType.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0027_auto_20211123_1605"),
        ("event_log", "0001_initial"),
    ]

    operations = [migrations.RunPython(insert_event_types, delete_event_types)]
