# Generated by Django 3.2.9 on 2021-12-03 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0028_data_event_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resourcingrequest",
            name="type",
            field=models.SmallIntegerField(choices=[(1, "New")], default=1),
        ),
    ]
