# Generated by Django 3.2.9 on 2021-12-06 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0029_alter_resourcingrequest_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="interimrequest",
            name="part_b_main_reason",
            field=models.TextField(
                help_text="What are the main reasons why this role has not been filled by a substantive Civil Servant. Please detail the strategic workforce plan for this role after the assignment end date:",
                verbose_name="Main reason",
            ),
        ),
    ]
