# Generated by Django 3.2.9 on 2021-12-06 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0030_alter_interimrequest_part_b_main_reason"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resourcingrequest",
            name="full_name",
            field=models.CharField(
                max_length=255, verbose_name="Contractor's full name"
            ),
        ),
    ]
