# Generated by Django 3.2.9 on 2021-12-06 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0031_alter_resourcingrequest_full_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cestrationale",
            name="role_description",
        ),
    ]
