# Generated by Django 3.2.9 on 2021-12-06 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0032_remove_cestrationale_role_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sdsstatusdetermination",
            name="completed_by",
        ),
    ]
