# Generated by Django 3.2.9 on 2021-12-06 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0033_remove_sdsstatusdetermination_completed_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cestrationale",
            name="how",
            field=models.TextField(verbose_name="Control & Direction: how"),
        ),
        migrations.AlterField(
            model_name="cestrationale",
            name="what",
            field=models.TextField(verbose_name="Control & Direction: what"),
        ),
        migrations.AlterField(
            model_name="cestrationale",
            name="when",
            field=models.TextField(verbose_name="Control & Direction: when"),
        ),
        migrations.AlterField(
            model_name="cestrationale",
            name="where",
            field=models.TextField(verbose_name="Control & Direction: where"),
        ),
    ]
