# Generated by Django 3.2.9 on 2021-12-07 17:49

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0035_remove_resourcingrequest_full_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="sdsstatusdetermination",
            name="contract_end_date",
            field=models.DateField(default=datetime.date.today),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="sdsstatusdetermination",
            name="contract_start_date",
            field=models.DateField(default=datetime.date.today),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="sdsstatusdetermination",
            name="worker_name",
            field=models.CharField(
                default="Test Worker", max_length=255, verbose_name="worker's name"
            ),
            preserve_default=False,
        ),
    ]
