# Generated by Django 3.2.9 on 2021-12-09 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0036_auto_20211207_1749"),
    ]

    operations = [
        migrations.CreateModel(
            name="Profession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
    ]
