# Generated by Django 3.2.9 on 2021-12-08 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0036_auto_20211207_1749"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resourcingrequest",
            name="state",
            field=models.SmallIntegerField(
                choices=[
                    (0, "Draft"),
                    (1, "Awaiting approvals"),
                    (2, "Amending"),
                    (3, "Amendments review"),
                    (4, "Approved"),
                ],
                default=0,
                verbose_name="Status",
            ),
        ),
    ]
