# Generated by Django 3.2.9 on 2021-12-09 11:01

from django.db import migrations


PROFESSIONS = (
    (1, "Development"),
    (2, "Data Science"),
)


def insert_professions(apps, schema_editor):
    Profession = apps.get_model("main", "Profession")

    for pk, name in PROFESSIONS:
        Profession.objects.create(pk=pk, name=name)


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0037_profession"),
    ]

    operations = [
        migrations.RunPython(insert_professions),
    ]
