# Generated by Django 3.2.9 on 2021-12-09 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0038_data_profession"),
    ]

    operations = [
        migrations.AddField(
            model_name="resourcingrequest",
            name="profession",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="main.profession",
            ),
            preserve_default=False,
        ),
    ]
