# Generated by Django 3.2.9 on 2021-12-09 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0037_alter_resourcingrequest_state"),
        ("main", "0039_resourcingrequest_profession"),
    ]

    operations = []
