# Generated by Django 3.2.9 on 2021-12-17 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0041_data_event_type"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="approval",
            options={
                "ordering": ["-timestamp"],
                "permissions": (
                    (
                        "can_give_head_of_profession_approval",
                        "Can give head of profession approval",
                    ),
                    ("can_give_busops_approval", "Can give BusOps approval"),
                    ("can_give_chief_approval", "Can give chief approval"),
                    ("can_give_hrbp_approval", "Can give HRBP approval"),
                    ("can_give_finance_approval", "Can give finance approval"),
                    ("can_give_commercial_approval", "Can give commercial approval"),
                    ("can_give_director_approval", "Can give director approval"),
                    ("can_give_dg_coo_approval", "Can give DG COO approval"),
                ),
            },
        ),
        migrations.RemoveField(
            model_name="resourcingrequest",
            name="director_general_approval",
        ),
        migrations.AddField(
            model_name="resourcingrequest",
            name="dg_coo_approval",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="dg_coo_approval",
                to="main.approval",
            ),
        ),
        migrations.AlterField(
            model_name="approval",
            name="type",
            field=models.CharField(
                choices=[
                    ("head_of_profession", "Head of Profession"),
                    ("chief", "Chief"),
                    ("busops", "BusOps"),
                    ("hrbp", "HRBP"),
                    ("finance", "Finance"),
                    ("commercial", "Commercial"),
                    ("director", "Director"),
                    ("dg_coo", "DG COO"),
                ],
                max_length=20,
            ),
        ),
    ]
