# Generated by Django 3.2.9 on 2021-12-20 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0043_auto_20211220_0938'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcingrequest',
            name='portfolio',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
