# Generated by Django 3.2.9 on 2021-12-20 10:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("main", "0044_resourcingrequest_portfolio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resourcingrequest",
            name="chief",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Chief/SMT sponsor",
            ),
        ),
    ]
