# Generated by Django 3.2.9 on 2021-12-20 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0045_alter_resourcingrequest_chief"),
    ]

    operations = [
        migrations.AddField(
            model_name="financialinformation",
            name="second_timesheet_validator",
            field=models.CharField(
                default="Mrs Anna Manager",
                max_length=255,
                verbose_name="name of the second timesheet & txpenses validator",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="financialinformation",
            name="timesheet_and_expenses_validator",
            field=models.CharField(
                max_length=255,
                verbose_name="name of the first timesheet & expenses validator",
            ),
        ),
    ]
