# Generated by Django 3.2.9 on 2021-12-20 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0046_auto_20211220_1047"),
    ]

    operations = [
        migrations.AlterField(
            model_name="financialinformation",
            name="second_timesheet_validator",
            field=models.CharField(
                max_length=255,
                verbose_name="name of the second timesheet & expenses validator",
            ),
        ),
    ]
