# Generated by Django 3.2.11 on 2022-01-05 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0047_alter_financialinformation_second_timesheet_validator"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="approval",
            options={
                "ordering": ["-timestamp"],
                "permissions": (
                    (
                        "can_give_head_of_profession_approval",
                        "Can give head of profession approval",
                    ),
                    (
                        "can_give_busops_approval",
                        "Can give workforce planning approval",
                    ),
                    ("can_give_chief_approval", "Can give chief approval"),
                    ("can_give_hrbp_approval", "Can give HRBP approval"),
                    ("can_give_finance_approval", "Can give finance approval"),
                    ("can_give_commercial_approval", "Can give commercial approval"),
                    ("can_give_director_approval", "Can give director approval"),
                    ("can_give_dg_coo_approval", "Can give DG COO approval"),
                ),
            },
        ),
        migrations.AlterField(
            model_name="approval",
            name="type",
            field=models.CharField(
                choices=[
                    ("head_of_profession", "Head of Profession"),
                    ("chief", "Chief"),
                    ("busops", "Workforce Planning"),
                    ("hrbp", "HRBP"),
                    ("finance", "Finance"),
                    ("commercial", "Commercial"),
                    ("director", "Director"),
                    ("dg_coo", "DG COO"),
                ],
                max_length=20,
            ),
        ),
    ]
