# Generated by Django 3.2.11 on 2022-01-07 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0049_auto_20220105_0925"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="interimrequest",
            name="overseas_country",
        ),
    ]
