# Generated by Django 3.2.11 on 2022-01-07 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("countries", "0003_auto_20220107_1434"),
        ("main", "0050_remove_interimrequest_overseas_country"),
    ]

    operations = [
        migrations.AddField(
            model_name="interimrequest",
            name="overseas_country",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="countries.country",
                verbose_name="if overseas which country?",
            ),
        ),
    ]
