# Generated by Django 3.2.11 on 2022-01-11 16:39

from django.db import migrations

import quill.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0053_add_completed_event_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobdescription",
            name="description",
            field=quill.db.models.fields.QuillField(default=dict),
        ),
    ]
