# Generated by Django 3.2.11 on 2022-01-14 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0054_jobdescription_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="jobdescription",
            name="essential_and_preferred_experience",
        ),
        migrations.RemoveField(
            model_name="jobdescription",
            name="key_accountabilities",
        ),
        migrations.RemoveField(
            model_name="jobdescription",
            name="line_management_responsibility",
        ),
        migrations.RemoveField(
            model_name="jobdescription",
            name="personal_attributes_and_skills",
        ),
        migrations.RemoveField(
            model_name="jobdescription",
            name="role_purpose",
        ),
        migrations.RemoveField(
            model_name="jobdescription",
            name="title",
        ),
    ]
