# Generated by Django 3.2.11 on 2022-01-14 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0055_auto_20220114_1434"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CestRationale",
        ),
    ]
