# Generated by Django 3.2.11 on 2022-01-21 14:57

from django.db import migrations


def set_area_of_work_to_ddat(apps, schema_editor):
    FinancialInformation = apps.get_model("main", "FinancialInformation")

    for fi in FinancialInformation.objects.all():
        fi.area_of_work = "ddat"
        fi.save()


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0057_financialinformation_team"),
    ]

    operations = [migrations.RunPython(set_area_of_work_to_ddat)]
