# Generated by Django 3.2.11 on 2022-01-21 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0058_auto_20220121_1457"),
    ]

    operations = [
        migrations.AlterField(
            model_name="financialinformation",
            name="area_of_work",
            field=models.CharField(
                choices=[("ddat", "DDaT")],
                max_length=255,
                verbose_name="Area of work for VAT reclaim",
            ),
        ),
    ]
