# Generated by Django 3.2.11 on 2022-01-24 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0059_alter_financialinformation_area_of_work"),
    ]

    operations = [
        migrations.AlterField(
            model_name="financialinformation",
            name="second_timesheet_validator",
            field=models.CharField(
                max_length=255,
                verbose_name="name of the second timesheet and expenses validator",
            ),
        ),
        migrations.AlterField(
            model_name="financialinformation",
            name="timesheet_and_expenses_validator",
            field=models.CharField(
                max_length=255,
                verbose_name="name of the first timesheet and expenses validator",
            ),
        ),
    ]
