# Generated by Django 3.2.11 on 2022-01-24 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0060_auto_20220124_1057"),
    ]

    operations = [
        migrations.AlterField(
            model_name="interimrequest",
            name="contractor_type",
            field=models.CharField(
                choices=[("generalist", "Generalist"), ("specialist", "Specialist")],
                max_length=50,
                verbose_name="Category of interim",
            ),
        ),
        migrations.AlterField(
            model_name="interimrequest",
            name="type_of_security_clearance",
            field=models.CharField(
                choices=[("BPSS", "BPSS"), ("sc", "SC"), ("dv", "DV"), ("ctc", "CTC")],
                max_length=50,
                verbose_name="Level of security clearance required",
            ),
        ),
    ]
