# Generated by Django 3.2.11 on 2022-01-24 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0061_auto_20220124_1058"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resourcingrequest",
            name="is_ir35",
            field=models.BooleanField(
                choices=[(True, "Yes"), (False, "No")],
                help_text='IR35 covers off-payroll working rules. So inside IR35 contractors not on the payroll pay broadly the same Income Tax and National Insurance contributions as employees. You can read more about IR35 <a class="govuk-link" href="https://www.gov.uk/guidance/understanding-off-payroll-working-ir35" target="_blank">here</a>.',
                null=True,
                verbose_name="Is the role inside IR35?",
            ),
        ),
    ]
