# Generated by Django 3.2.11 on 2022-01-25 09:48

import django.core.validators
from django.db import migrations, models

import main.models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0062_alter_resourcingrequest_is_ir35"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cestdocument",
            name="file",
            field=models.FileField(
                help_text='Use the <a class="govuk-link" target="_blank" href="https://www.gov.uk/guidance/check-employment-status-for-tax">CEST tool</a> and upload the PDF file output.<br>The link to the document is only valid for 5 minutes. After this, you will need to refresh the page to get a new link.',
                upload_to=main.models.resourcing_request_directory_path,
                validators=[django.core.validators.FileExtensionValidator(["pdf"])],
            ),
        ),
        migrations.AlterField(
            model_name="interimrequest",
            name="contractor_type",
            field=models.CharField(
                choices=[("generalist", "Generalist"), ("specialist", "Specialist")],
                max_length=50,
                verbose_name="Type of interim required",
            ),
        ),
        migrations.AlterField(
            model_name="interimrequest",
            name="part_b_business_case",
            field=models.TextField(
                help_text="Explain why an interim resource is needed.",
                verbose_name="Business case",
            ),
        ),
        migrations.AlterField(
            model_name="interimrequest",
            name="part_b_impact",
            field=models.TextField(
                help_text="Explain the impact of not getting this resource.",
                verbose_name="Impact",
            ),
        ),
        migrations.AlterField(
            model_name="interimrequest",
            name="part_b_main_reason",
            field=models.TextField(
                help_text="Why has this role not been filled by a substantive civil servant? What is the strategic workforce plan for this role after the contract end date?",
                verbose_name="Justification",
            ),
        ),
    ]
