# Generated by Django 3.2.11 on 2022-01-25 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0063_auto_20220125_0948"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sdsstatusdetermination",
            options={"verbose_name": "status determination statement (SDS)"},
        ),
        migrations.AlterField(
            model_name="approval",
            name="reason",
            field=models.OneToOneField(
                help_text="You need to provide a reason for rejection, if you approve then you don't have to add a note.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reason",
                to="main.comment",
                verbose_name="Explanation",
            ),
        ),
        migrations.AlterField(
            model_name="approval",
            name="type",
            field=models.CharField(
                choices=[
                    ("head_of_profession", "Head of Profession"),
                    ("chief", "Chief"),
                    ("busops", "Workforce Planning"),
                    ("hrbp", "HR Business Partners"),
                    ("finance", "Finance"),
                    ("commercial", "Commercial"),
                    ("director", "Director"),
                    ("dg_coo", "DG COO"),
                ],
                max_length=20,
                verbose_name="role",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="text",
            field=models.TextField(
                help_text="You can add a comment at any stage of the process. Use these to provide further information. Approval and rejection notes will also appear here.",
                verbose_name="Add a comment",
            ),
        ),
    ]
