# Generated by Django 3.2.11 on 2022-02-02 09:00

import django.core.validators
from django.db import migrations, models

import main.models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0064_auto_20220125_1126"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cestdocument",
            name="file",
            field=models.FileField(
                help_text='Use the <a class="govuk-link" target="_blank" href="https://www.gov.uk/guidance/check-employment-status-for-tax">CEST tool</a>, this will generate a PDF which should be uploaded here.<br>The link to the current file will time out after 5 minutes. If it has timed out, refresh the page to update the link.',
                upload_to=main.models.resourcing_request_directory_path,
                validators=[django.core.validators.FileExtensionValidator(["pdf"])],
            ),
        ),
    ]
