# Generated by Django 3.2.12 on 2022-02-28 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0066_auto_20220224_0956"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={"ordering": ["-timestamp"]},
        ),
    ]
