# Generated by Django 3.2.12 on 2022-03-01 09:24

from django.db import migrations


EVENT_TYPES = ((14, "APPROVAL_CLEARED", "The approval was cleared"),)


def insert_event_types(apps, schema_editor):
    EventType = apps.get_model("event_log", "EventType")

    for pk, code, name in EVENT_TYPES:
        EventType.objects.create(pk=pk, code=code, name=name)


def delete_event_types(apps, schema_editor):
    EventType = apps.get_model("event_log", "EventType")

    for pk, _, _ in EVENT_TYPES:
        EventType.objects.get(pk=pk).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0067_alter_comment_options"),
    ]

    operations = [migrations.RunPython(insert_event_types, delete_event_types)]
