# Generated by Django 3.2.9 on 2021-12-09 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0040_merge_20211209_1432"),
        ("user", "0002_user_profession"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profession",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="main.profession",
            ),
        ),
    ]
