# Generated by Django 3.2.11 on 2022-01-26 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_alter_user_profession"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="summary_config",
            field=models.JSONField(default=dict),
        ),
    ]
