# Generated by Django 3.2.11 on 2022-01-28 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_user_summary_config"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="preferred_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
